export default {
  deviceId: '123456789012345678901234',
  features: ['warming', 'cooling'],
  firmwareUpdated: true,
  firmwareUpdating: false,
  firmwareVersion: '2.3.18.0',
  hasWater: true,
  hubInfo: '12345-0001-A01-AABBCCDD',
  lastHeard: '2020-06-21T03:36:57.441Z',
  lastLowWater: '2020-03-04T21:10:38.334Z',
  lastPrime: '2020-03-04T21:11:23.746Z',
  ledBrightnessLevel: 30,
  leftHeatingDuration: 0,
  leftHeatingLevel: -15,
  leftKelvin: {
    active: false,
    alarms: [],
    currentActivity: 'off',
    currentTargetLevel: 0,
    level: 0,
    scheduleProfiles: [
      {
        enabled: true,
        startLocalTime: '22:00:00',
        weekDays: {
          friday: true,
          monday: true,
          saturday: true,
          sunday: true,
          thursday: true,
          tuesday: true,
          wednesday: true,
        },
      },
    ],
    targetLevels: [-10, -10, -20],
  },
  leftNowHeating: false,
  leftSchedule: {
    daysUTC: {
      friday: false,
      monday: false,
      saturday: false,
      sunday: false,
      thursday: false,
      tuesday: false,
      wednesday: false,
    },
    durationSeconds: 0,
    enabled: false,
    startUTCHour: 0,
    startUTCMinute: 0,
  },
  leftTargetHeatingLevel: 0,
  leftUserId: '1234567890abcdef123456789011111',
  location: [-122.32171311, 37.55987324],
  mattressInfo: {
    brand: null,
    eightMattress: null,
    firstUsedDate: null,
  },
  needsPriming: false,
  online: true,
  ownerId: '1234567890abcdef123456789011111',
  priming: false,
  rightHeatingDuration: 3575,
  rightHeatingLevel: 21,
  rightKelvin: {
    active: true,
    alarms: [],
    currentActivity: 'schedule',
    currentTargetLevel: 50,
    level: 50,
    phases: [
      {
        active: false,
        operation: 'on',
        position: 0,
      },
      {
        active: true,
        level: 50,
        operation: 'temperature',
        position: 0,
      },
      {
        active: false,
        level: 10,
        operation: 'temperature',
        position: 0.33,
      },
      {
        active: false,
        level: 30,
        operation: 'temperature',
        position: 0.67,
      },
      {
        active: false,
        operation: 'off',
        position: 1,
      },
    ],
    scheduleProfiles: [
      {
        enabled: true,
        startLocalTime: '21:30:00',
        weekDays: {
          friday: true,
          monday: true,
          saturday: true,
          sunday: true,
          thursday: true,
          tuesday: true,
          wednesday: true,
        },
      },
    ],
    targetLevels: [50, 10, 30],
  },
  rightNowHeating: true,
  rightSchedule: {
    daysUTC: {
      friday: false,
      monday: false,
      saturday: false,
      sunday: false,
      thursday: false,
      tuesday: false,
      wednesday: false,
    },
    durationSeconds: 0,
    enabled: false,
    startUTCHour: 0,
    startUTCMinute: 0,
  },
  rightTargetHeatingLevel: 50,
  rightUserId: '1234567890abcdef123456789022222',
  sensorInfo: {
    connected: true,
    hwRevision: 'A01',
    label: '12345-0001-A01-00000000',
    lastConnected: '2020-06-21T03:36:57.441Z',
    partNumber: '12345',
    serialNumber: '00000000',
    sku: '0001',
    skuName: 'queen',
  },
  timezone: 'America/Los_Angeles',
}
